name: Test CI

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        container: ghcr.io/josen-b/tangram-crates

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

              run: |
                chmod +x scripts/tests.sh
                ./scripts/tests.sh --auto --sequential
